# Generated by Django 5.0.2 on 2024-03-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0001_initial"),
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testschedule",
            name="classroom",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="classroom.classroommodel",
            ),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"is_faculty": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"is_faculty": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
