# Generated by Django 5.0.2 on 2024-03-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0001_initial"),
        (
            "dashboard",
            "0002_testschedule_classroom_alter_testschedule_faculty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testschedule",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classroom.classroommodel",
            ),
        ),
    ]
