# Generated by Django 5.0.2 on 2024-03-04 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_testschedule_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 3, 4, 16, 0, 17, 229175, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
