# Generated by Django 5.0.2 on 2024-03-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_timetable_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="timetable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.timetable",
            ),
            preserve_default=False,
        ),
    ]
